name: Deploy whatshafiz.com

on:
  push:
    branches:
      - main

jobs:

  deploy:
    name: 'Deploy To S3'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      # Bump latest release version by the default_bump and push the new tag
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        id: version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main
          DEFAULT_BUMP: ${{ secrets.VERSION_BUMP }}

      # Deploy code to s3 bucket for the website
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-central-1'
